spring:

  application:
    name: monitor-subscription-matcher

  kafka:
    bootstrap-servers: ${KAFKA_BROKER_ADDR:kafka3:9092}
    consumer:
      filing:
        topic: ${FILING_TOPIC:monitor-filing}
        group-id: ${FILING_CONSUMER_GROUP_NAME:monitor-filing-consumer-group}
        max-attempts: ${MAX_ATTEMPTS:5}
        backoff-delay: ${BACKOFF_DELAY:1000}
        concurrency: ${CONCURRENT_LISTENER_INSTANCES:1}
    producer:
      notify:
        topic: ${NOTIFICATION_MATCH_TOPIC:notification-match}

  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://mongo:27017}
      database: ${MONGO_DATABASE:monitor}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /monitor-subscription-matcher
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      access: read_only
      show-details: always
  health:
    defaults:
      enabled: true
    mongo:
      enabled: false

server:
  port: ${PORT:8181}

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients: DEBUG